name       : d-feet
version    : 0.3.15
release    : 3
source     :
    - http://download.gnome.org/sources/d-feet/0.3/d-feet-0.3.15.tar.xz : 1fff149ad01ccbd93c927f5733346a9122324b9d367da3adbf4f1a52e47dfdb1
license    : GPL-2.0-or-later
component  : programming.tools
summary    : D-Feet is an easy to use D-Bus debugger.
description: |
    D-Bus is a messaging library used on the Desktop. D-Feet can be used to inspect D-Bus interfaces of running programs and invoke methods on those interfaces.
builddeps  :
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(python3)
    - itstool
rundeps    :
    - python-gobject
setup      : |
    %meson_configure -Dtests=false
build      : |
    %ninja_build
install    : |
    %ninja_install
